name: budget_manager
description: Uma aplicação moderna de gestion de budget com Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.1.0
  
  
  flutter_local_notifications: ^17.2.3
  
  provider: ^6.1.1
  
  intl: ^0.20.2
  
  syncfusion_flutter_charts: ^32.1.19
  syncfusion_flutter_core: ^32.1.19
  
  shimmer: ^3.0.0
  
  lottie: ^3.3.2
  
  flutter_svg: ^2.0.9
  
  
  table_calendar: ^3.2.0
  
  percent_indicator: ^4.2.3
  
  google_fonts: ^6.1.0
  
  path_provider: ^2.1.0
  timezone: ^0.9.4
  
  shared_preferences: ^2.2.2
  
  http: ^1.1.0
  dio: ^5.3.2
  
  csv: ^6.0.0
  pdf: ^3.10.4
  
  openai_dart: ^0.6.0+1
  
  share_plus: ^12.0.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
